version: "3.2"

services:
  postgresql:
    image: postgres
    container_name: project-postgresql
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - "POSTGRES_DB=app"
      - "POSTGRES_USER=dev"
      - "POSTGRES_PASSWORD=dev"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - app-network
    
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
    
  
