version: "3.2"

services:
  project:
    build:
      context: ../../../../
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: project
    ports:
      - 8080:8080
    environment:
      - "QUARKUS_PROFILE=dev"
      - "QUARKUS_DATASOURCE_DB_KIND=postgresql"
      - "QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://project-postgresql:5432/app?reWriteBatchedInserts=true&amp"
      - "QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver"  
    networks: 
      - app-network   

networks:
  app-network:
    driver: bridge
  